using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace EQ_Zip
{
    public partial class formAbout : Form
    {
        public string VersionNumber;

        private string Description = @"e1xydGYxXGFuc2lcYW5zaWNwZzEyNTJcZGVmZjBcbm91aWNvbXBhdFxkZWZsYW5nMTAzM1xkZWZsYW5nZmUxMDMze1xmb250dGJse1xmMFxmc3dpc3NcZnBycTJcZmNoYXJzZXQwIENhbGlicmk7fXtcZjFcZnJvbWFuXGZwcnEyXGZjaGFyc2V0MiBTeW1ib2w7fX0NCntcY29sb3J0YmwgO1xyZWQwXGdyZWVuMFxibHVlMjU1O30NCntcKlxnZW5lcmF0b3IgUmljaGVkMjAgNi4zLjk2MDB9XHZpZXdraW5kNFx1YzEgDQpccGFyZFxxalxmMFxmczI0IFRoaXMgYXBwbGljYXRpb24gaXMgYSBsYWJvciBvZiBsb3ZlIGZyb20gYSBodWdlIGRpZS1oYXJkIGZhbiBvZiBFdmVyUXVlc3QgYW5kIHRoZSBFdmVyUXVlc3QgZnJhbmNoaXNlLiBJdCBpcyBtZXJlbHkgaW50ZW5kZWQgdG8gc2ltcGxpZnkgdGhlIHByb2Nlc3Mgb2YgYWxsb3dpbmcgcGxheWVycyB0byBzd2FwIG91dCB0ZXh0dXJlcyBhbmQgc291bmQgZWZmZWN0cyBpbiB0aGVpciBsZWdhbGx5IGFjcXVpcmVkIGNsaWVudCBmaWxlcy5ccGFyDQpccGFyDQpFdmVyUXVlc3QgaXMgMTYgeWVhcnMgb2xkIGF0IHRoZSB0aW1lIG9mIHRoaXMgd3JpdGluZywgYW5kIG1vc3Qgb2YgdGhlIG9sZGVyIHpvbmVzIGNvbnRpbnVlIHRvIHVzZSB2ZXJ5IG9sZCAyNTZ4MjU2IGxvc3N5LWNvbXByZXNzZWQgdGV4dHVyZXMuIFN3YXBwaW5nIHRoZW0gb3V0IGZvciBsYXJnZXIsIHVuY29tcHJlc3NlZCB0ZXh0dXJlcyBnaXZlcyB0aGUgZ2FtZSB3aG9sZSBuZXcgbGlmZSwgd2l0aG91dCBhZmZlY3RpbmcgZ2FtZXBsYXkgb3IgcHJvdmlkaW5nIGFueSBzb3J0IG9mIGdhbWVwbGF5IGFkdmFudGFnZS5ccGFyDQpccGFyDQpFUS1aaXAgaXMgbm90IGFmZmlsaWF0ZWQgd2l0aCwgZW5kb3JzZWQgYnksIGFwcHJvdmVkIGJ5LCBvciBpbiBhbnkgd2F5IGFzc29jaWF0ZWQgd2l0aCBEYXlicmVhayBHYW1lcywgdGhlIEV2ZXJRdWVzdCBmcmFuY2hpc2UsIG9yIGFueSBvZiB0aGUgb3RoZXIgY29tcHJlc3Npb24vYXJjaGl2ZSBiYXNlZCBhcHBsaWNhdGlvbnMgb3V0IHRoZXJlIHdpdGggdGhlIHdvcmQgIlppcCIgaW4gdGhlbS5ccGFyDQpccGFyDQoNClxwYXJkIFRoaXMgRk9TUyBzb2Z0d2FyZSBpcyBwcm92aWRlZCB1bmRlciB0aGUgQ3JlYXRpdmUgQ29tbW9ucyBaZXJvIExpY2Vuc2UsIGEgc3VtbWFyeSBhbmQgdGhlIGZ1bGwgdGV4dCBvZiB3aGljaCBjYW4gYmUgZm91bmQgYXQgdGhlIGZvbGxvd2luZyBsb2NhdGlvbjpccGFyDQpccGFyDQpodHRwczovL2NyZWF0aXZlY29tbW9ucy5vcmcvcHVibGljZG9tYWluL3plcm8vMS4wL1xwYXINClxwYXINClRoZSBmdWxsIHNvdXJjZSBjb2RlIG9mIHRoaXMgcHJvamVjdCBjYW4gYmUgZm91bmQgb24gR2l0aHViIGF0IHRoZSBmb2xsb3dpbmcgbG9jYXRpb246XHBhcg0KDQpccGFyZFxxalxwYXINCg0KXHBhcmQgaHR0cHM6Ly9naXRodWIuY29tL1NoZW5kYXJlL0VRWmlwIFxwYXINCg0KXHBhcmRccWpccGFyDQoNClxwYXJkIEVuam95LCBmZWxsb3cgRXZlclF1ZXN0ZXJzLlxwYXINCg0KXHBhcmRccWpccGFyDQoNClxwYXJkXGZpLTM2MFxsaTcyMFxxaiAtXHRhYiBTaGVuZGFyZSAoSm9uIEQuIEphY2tzb24pXHBhcg0KDQpccGFyZFxxalxwYXINCkNyZWRpdHM6XHBhcg0KXHBhcg0KDQpccGFyZFxmaS0zNjBcbGk3MjBcZjFcJ2I3XHRhYlxmMCBFdmVyUXVlc3QgZ2FtZSBwYWNrYWdlIGZpbGUgZm9ybWF0IGRldGVybWluZWQgZnJvbSBleGFtaW5hdGlvbiBvZiB0aGUgRGVscGhpIGNvZGUgaW4gUzNEU3B5LCBieSBXaW5kY2F0Y2hlciwgd2l0aG91dCB3aG9zZSB3b3JrIHRoaXMgd291bGQgYmUgaW1wb3NzaWJsZS5cdGFiXHBhcg0KDQpccGFyZFxmaS0zNjBcbGk3MjBccWNccGFyIGh0dHA6Ly9zb3VyY2Vmb3JnZS5uZXQvcHJvamVjdHMvZXFlbXVsYXRvci9maWxlcy9PcGVuWm9uZS9TM0RTcHklMjAxLjMvIFxsaW5lXHBhcg0KDQpccGFyZFxmaS0zNjBcbGk3MjBcZjFcJ2I3XHRhYlxmMCBERFMgdGV4dHVyZSBmaWxlIHBhcnNpbmcgcmVidWlsdCBmcm9tIGNvZGUgYnkgTG9yZW56byBDb25zb2xhcm8uIChNSVQgTGljZW5zZSlcdGFiXHBhcg0KDQpccGFyZFxmaS0zNjBcbGk3MjBccWNccGFyIGh0dHBzOi8vY29kZS5nb29nbGUuY29tL3Ava3Byb2plY3RzLyBcbGluZVxwYXINCg0KXHBhcmRcZmktMzYwXGxpNzIwXGYxXCdiN1x0YWJcZjAgVEdBIGltYWdlIGxvYWRpbmcgY2xhc3MgZnJvbSBEYXZpZCBQb2xvbWlzLiAoQ1BPTCAxLjAyKVx0YWJccGFyDQoNClxwYXJkXGZpLTM2MFxsaTcyMFxxY1xwYXIgaHR0cDovL3d3dy5jb2RlcHJvamVjdC5jb20vQXJ0aWNsZXMvMzE3MDIvTkVULVRhcmdhLUltYWdlLVJlYWRlciBcbGluZVxwYXINCg0KXHBhcmRcZmktMzYwXGxpNzIwXGYxXCdiN1x0YWJcZjAgVmlydHVhbCBXaW5kb3dzIFNoZWxsIEZpbGUgaGFuZGxpbmcgZnVuY3Rpb25hbGl0eSB0aGFua3MgdG8gRGF2aWQgQW5zb24gKE1JVCBMLilcdGFiXHBhcg0KDQpccGFyZFxmaS0zNjBcbGk3MjBccWNccGFyIGh0dHBzOi8vZGxhYS5tZS9ibG9nL3Bvc3QvOTkyMzA3MiBcbGluZVxwYXINCg0KXHBhcmRcZmktMzYwXGxpNzIwXGYxXCdiN1x0YWJcZjAgSWNvbnMgbWFkZSBmcm9tIHRoZSBmcmVld2FyZSBub24tY29tbWVyY2lhbCAiQXF1YSBOZXVlIChHcmFwaGl0ZSkiIHBhY2suXGxpbmVccGFyDQp9";
        
        public formAbout()
        {
            InitializeComponent();
        }

        private void formAbout_Load(object sender, EventArgs e)
        {
            this.Text = "About EQ-Zip " + VersionNumber;

            using (MemoryStream _text = new MemoryStream(System.Convert.FromBase64String(Description)))
            {
                richTextBox1.LoadFile(_text, RichTextBoxStreamType.RichText);
            }
        }

        private void richTextBox1_LinkClicked(object sender, LinkClickedEventArgs e)
        {
            System.Diagnostics.Process.Start(e.LinkText);
        }
    }
}
